#!/bin/bash
# Author: Michael Gebetsroither <michael@mgeb.org>

binaries-callable() {
    errors_=0
    for i in $(ls bin/*); do
        out_="$($i --help)"
        bin_="$(basename $i)"
        if ! echo "$out_" |grep -q "Usage: $bin_"; then
            errors_=$(( $errors_ + 1 ))
            echo "Error getting usage from: $bin_"
            echo "$out_"
        fi
    done
    echo "binaries-callable fails $errors_ of $(ls bin/*|wc -l) tests"
    if (( $errors_ != 0 )); then
        exit 1
    else
        exit 0
    fi
}

unit() {
    t_="$1"
    exec /usr/bin/python ./run_doctest.py "ooopy/$1"
}

all_tests() {
    ret_=0
    for i in binaries-callable unit-transformer unit-ooopy; do
        if ! $0 $i; then
            ret_=1
            echo "Error: test-failure for $i"
        fi
    done
    exit $ret_
}

case "$1" in
    "all") all_tests ;;
    "binaries-callable") binaries-callable ;;
    "unit-transformer") unit "Transformer.py" ;;
    "unit-ooopy" ) unit "OOoPy.py" ;;
    *) echo "Unknown test-name" >&2; exit 1 ;;
esac
